services:
  - type: web
    name: ai-security-backend
    runtime: python
    plan: free # Para que no te cobren
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
